{{- if .Values.auto.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "opennebula.name" . }}-api-access
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "opennebula.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "30"
    "helm.sh/hook-delete-policy": before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "opennebula.name" . }}-api-access
subjects:
- kind: ServiceAccount
  name: {{ template "opennebula.name" . }}-api
  namespace: {{ .Release.Namespace }}
{{- end }}
