{{- if .Values.auto_ssh.delete.enable }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "opennebula.name" . }}-ssh-keys
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    app: {{ template "opennebula.name" . }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy":  hook-succeeded
spec:
  template:
    metadata:
      name: {{ template "opennebula.name" . }}-ssh-keys-delete
      labels:
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        app: {{ template "opennebula.name" . }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        release: {{ .Release.Name }}
        component: pre-delete
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "opennebula.name" . }}-api
      automountServiceAccountToken: true
      containers:
        - name: pre-delete
          image: "{{ .Values.auto_ssh.image }}:{{ .Values.auto_ssh.tag }}"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command: 
            - "/bin/sh"
            - "-ec"
            - |
              curl -s -X DELETE -k https://kubernetes.default.svc/api/v1/namespaces/${NAMESPACE}/secrets/{{ include "opennebula.fullname" . }}-ssh-keys \
                -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" \
                -H "Content-Type: application/json" \
                -H "Accept: application/json" \
                -d "{ \"kind\": \"Secret\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"{{ include "opennebula.fullname" . }}-ssh-keys\", \"namespace\": \"${NAMESPACE}\" } }" > /dev/null && \
              curl -s -X DELETE -k https://kubernetes.default.svc/api/v1/namespaces/${NAMESPACE}/secrets/{{ include "opennebula.fullname" . }}-serveradmin \
                -H "Authorization: Bearer $( cat /var/run/secrets/kubernetes.io/serviceaccount/token )" \
                -H "Content-Type: application/json" \
                -H "Accept: application/json" \
                -d "{ \"kind\": \"Secret\", \"apiVersion\": \"v1\", \"metadata\": { \"name\": \"{{ include "opennebula.fullname" . }}-serveradmin\", \"namespace\": \"${NAMESPACE}\" } }" > /dev/null
{{- end }}
