apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "opennebula.sunstone.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  name: {{ template "opennebula.node.fullname" . }}
spec:
  serviceName: {{ template "opennebula.node.fullname" . }}
  selector:
    matchLabels:
      app: {{ template "opennebula.node.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "opennebula.node.fullname" . }}
        release: {{ .Release.Name }}
    spec:
    {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml .Values.imagePullSecrets}}
    {{- end }}
      containers:
      #######
      - image: "{{ .Values.hosts.image.repository }}:{{ .Values.hosts.image.tag }}"
        name: {{ template "opennebula.node.fullname" . }}-libvirt
        args: ["libvirt"]
        securityContext:
          # privileged: true
          capabilities:
            add: ["NET_ADMIN"]    
      - image: "{{ .Values.hosts.image.repository }}:{{ .Values.hosts.image.tag }}"
        name: {{ template "opennebula.node.fullname" . }}-sshd
        args: ["sshd"]
        securityContext:
          # privileged: true
          capabilities:
            add: ["NET_ADMIN"]    
      {{- if .Values.pullSecrets }}
        imagePullSecrets:
          {{ toYaml .Values.pullSecrets}}
      {{- end }}
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /var/lib/one/.ssh/authorized_keys
          name: oneadmin-ssh-keys
          subPath: authorized_keys
        - mountPath: /var/lib/one/.ssh/config
          name: oneadmin-ssh-keys
          subPath: config
      volumes:
      - configMap:
          name: {{ template "opennebula.node.fullname" . }}-config
        name: config
      - name: oneadmin-ssh-keys
        secret:
          secretName: opennebula-ssh-keys
      # hostIPC: false
      hostNetwork: true
      # hostPID: false
      {{- if .Values.hosts.nodeSelector }}
      nodeSelector:
        {{ toYaml .Values.hosts.nodeSelector }}
      {{- end }}
      {{- if .Values.hosts.tolerations }}
      tolerations:
        {{ toYaml .Values.hosts.tolerations }}
      {{- end }}
      {{- if .Values.hosts.affinity }}
      affinity:
        {{ toYaml .Values.hosts.affinity }}
      {{- end }}
