apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "opennebula.sunstone.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: {{ template "opennebula.node.fullname" . }}-config
data:
  somconfig.conf:
{{  tpl (toYaml .Values.hosts.config) . | indent 4 }}
