apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: {{ template "opennebula.sunstone.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
  name: {{ template "opennebula.sunstone.fullname" . }}
data:
  sunstone-server.conf: |
    :tmpdir: /var/tmp
    :one_xmlrpc: http://{{ template "opennebula.oned.fullname" . }}:{{ .Values.onedeamon.service.port }}/RPC2
    :one_xmlrpc_timeout: 60
    :host: 0.0.0.0
    :port: 9869
    :sessions: {{ .Values.sunstone.config.sessions }} 
    :memcache_host: {{ template "opennebula.memcached.fullname" . }} 
    :memcache_port: {{ .Values.sunstone.config.memcached.port }}
    :memcache_namespace: opennebula.sunstone
    :env: 'prod'
    :debug_level: {{ .Values.debug_level | default 2 }}
    :auth: {{ .Values.sunstone.config.auth | default "opennebula" }}
    :core_auth: {{ .Values.sunstone.config.core_auth | default "cipher" }}
    :remote_version: http://downloads.opennebula.org/latest
    :vnc_proxy_port: 29876
    :vnc_client_port: 443/websockify
    :vnc_proxy_support_wss: only
    :vnc_proxy_ipv6: false
    :vnc_request_password: false
    :keep_me_logged: true
    :lang: en_US
    :table_order: desc
    :mode: 'mixed'
    :marketplace_url: http://marketplace.opennebula.systems/
    :oneflow_server: http://opennebula-oneflow:2474/
    :routes:
        - oneflow
        #- vcenter
        - support
